<?php
/**

 * @version SOFORT Gateway 5.2.0 - $Date: 2012-09-06 13:49:09 +0200 (Thu, 06 Sep 2012) $

 * @author SOFORT AG (integration@sofort.com)

 * @link http://www.sofort.com/

 *

 * Copyright (c) 2012 SOFORT AG

 *

 * $Id: sofortInstall.php 3751 2012-10-10 08:36:20Z gtb-modified $

 */

//Notice: DB-field orders_status_name is varchar(32)!
//if following strings are longer, they will be cut!
define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_TEMP_GERMAN', 'Bezahlung schwebend');
define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_CONFIRMED_GERMAN', 'Bezahlung erfolgt');
define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_INVOICE_CONFIRMED_GERMAN', 'Bestätigt');
define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_UNCONFIRMED_GERMAN', 'Unbestätigt');
define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_CANCELED_GERMAN', 'Bezahlung storniert');
define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_CHECK_GERMAN', 'Prüfung notwendig');

define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_TEMP_ENGLISH', 'Payment pending');
define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_CONFIRMED_ENGLISH', 'Payment confirmed');
define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_INVOICE_CONFIRMED_ENGLISH', 'Confirmed');
define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_UNCONFIRMED_ENGLISH', 'Unconfirmed');
define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_CANCELED_ENGLISH', 'Payment canceled');
define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_CHECK_ENGLISH', 'Needs review.');

define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_TEMP_POLISH', 'P³atno¶æ w toku');
define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_CONFIRMED_POLISH', 'P³atno¶æ zosta³a zrealizowana.');
define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_INVOICE_CONFIRMED_POLISH', 'Bestätigt');
define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_UNCONFIRMED_POLISH', 'Rechnung noch nicht bestätigt');
define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_CANCELED_POLISH', 'P³atno¶æ anulowana');
define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_CHECK_POLISH', 'Prüfung notwendig');

define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_TEMP_DUTCH', 'In afwachting van betaling');
define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_CONFIRMED_DUTCH', 'Betaling afgesloten');
define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_INVOICE_CONFIRMED_DUTCH', 'Bestätigt');
define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_UNCONFIRMED_DUTCH', 'Rechnung noch nicht bestätigt');
define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_CANCELED_DUTCH', 'Betaling geannuleerd');
define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_CHECK_DUTCH', 'Prüfung notwendig');

define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_TEMP_FRENCH', 'Paiement en attente');
define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_CONFIRMED_FRENCH', 'Paiement confirmé');
define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_INVOICE_CONFIRMED_FRENCH', 'Confirmé');
define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_UNCONFIRMED_FRENCH', 'ne pas confirmé');
define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_CANCELED_FRENCH', 'Paiement annulé');
define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_CHECK_FRENCH', 'Vérification nécessaire');

define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_TEMP_ITALIAN', 'Pagamento in sospeso');
define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_CONFIRMED_ITALIAN', 'Pagamento eseguito');
define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_INVOICE_CONFIRMED_ITALIAN', 'Confermato');
define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_UNCONFIRMED_ITALIAN', 'Non confermata');
define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_CANCELED_ITALIAN', 'Pagamento annullato');
define('MODULE_PAYMENT_SOFORT_MULTIPAY_STATE_CHECK_ITALIAN', 'Verifica necessaria');
?>